---
title: "Appendix B"
subtitle: Complete R Code & Annotated Output
output:
  pdf_document:
    toc: false
    latex_engine: xelatex
    keep_tex: true
geometry: left=1.5in,right=1in,top=1in,bottom=1in
header-includes:
- \usepackage{floatrow}
- \usepackage{booktabs}
- \usepackage{siunitx}
- \usepackage{caption}
- \usepackage{longtable}
- \usepackage{colortbl}
- \usepackage{array}
- \usepackage{caption}
- \usepackage{setspace}
- \usepackage{fancyhdr}
---


\pagenumbering{arabic}
\setcounter{page}{100}
\fancypagestyle{plain}{%
    \renewcommand{\headrulewidth}{0pt}%
      \fancyhf{}%
    \fancyhead[R]{\thepage}
    \setlength\voffset{0.25in}
    }
\pagestyle{plain}



\setcounter{figure}{0}
\setcounter{table}{0}
\captionsetup{labelfont=bf, 
              textfont={it}, 
              labelsep=newline,
              justification=raggedright, 
              singlelinecheck=false}
\floatsetup[figure]{capposition=top}
\floatsetup[table]{capposition=top}
\renewcommand{\thefigure}{B.\arabic{figure}}
\renewcommand{\thetable}{B.\arabic{table}}



\clearpage
\setcounter{tocdepth}{2}
\tableofcontents    
\clearpage
\listoftables
\clearpage
\listoffigures
\clearpage


```{r, include=FALSE}
knitr::opts_chunk$set(comment     = "",
                      echo        = TRUE,
                      warning     = FALSE, 
                      message     = FALSE,
                      ft.align    ="left",
                      fig.pos     = "hb",     
                      fig.align   = "left",   
                      fig.width   = 5,     
                      fig.height  = 3)  
```


# BACKGROUND

> This dataset if publicly available online as part of a seminar on "[DECOMPOSING, PROBING, AND PLOTTING INTERACTIONS IN R](https://stats.oarc.ucla.edu/r/seminars/interactions-r/)"
> - UCLA Advanced Research Computing: Statistical Methods and Data Analysis

## Motivation

> Suppose you are doing a simple study on weight loss and notice that people who spend more time exercising lose more weight. Upon further analysis you notice that those who spend the same amount of time exercising lose more weight if they are more effortful. The more effort people put into their workouts, the less time they need to spend exercising. This is popular in workouts like high intensity interval training (HIIT).

